// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type RegisterInput struct {
	Username        string `json:"username"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
	Email           string `json:"email"`
}
